spring.application.name=Fridge_Raid

file.upload-dir=C:/Users/dlwog/git/Fridge_Raid/Fridge_Raid/uploads
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.fridge_raid

