spring.application.name=Fridge_Raid
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.fridge_raid

file.upload-dir=C:/Users/jaehyuk/git/Fridge_Raid/Fridge_Raid/uploads